remote_theme: pages-themes/cayman@v0.2.0
title: Understanding GitHub Copilot
description: A comprehensive guide to every GitHub Copilot customization and agentic feature.
plugins:
  - jekyll-remote-theme
